# Generated by Django 6.0.5 on 2026-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('ad_type', models.CharField(choices=[('banner', 'Banner Ad'), ('rewarded', 'Rewarded Ad')], default='banner', max_length=20)),
                ('position', models.CharField(choices=[('homepage_top', 'Homepage Top Banner'), ('homepage_between_cards', 'Homepage Between Cards'), ('detail_below_images', 'Listing Detail Below Images'), ('phone_reveal', 'Phone Reveal Rewarded Ad')], max_length=50)),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
